# Generated by Django 3.2 on 2022-08-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lugar', models.CharField(max_length=150)),
                ('contenido', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de finalizacion')),
                ('gratuito', models.BooleanField(default=True, verbose_name='Gratis')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.modalidad')),
            ],
        ),
    ]
