# Generated by Django 3.2 on 2022-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220828_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad de dias a reservar'),
        ),
    ]
