# Generated by Django 3.2 on 2022-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_evento_cantidad_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
