# Generated by Django 3.2 on 2022-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_evento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gratuito',
            field=models.BooleanField(default=True, verbose_name='Gratis'),
        ),
    ]
