# Generated by Django 3.2 on 2022-08-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('fecha_de_comentario', models.DateTimeField(auto_now_add=True)),
                ('Noticia_Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='noticias.noticia')),
            ],
        ),
    ]
