# Generated by Django 3.2 on 2022-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_evento_gratuito'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
