# Generated by Django 3.2 on 2022-08-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
