# Generated by Django 3.2 on 2022-08-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_comentario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Noticia_Comentario',
            new_name='noticia_Comentario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='descripciones',
        ),
    ]
